# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  internal_url: "http://192.168.178.20:8123"  # your PC's LAN IP
  external_url: "http://192.168.178.20:8123"  # optional, same for dev
  allowlist_external_dirs: []

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.offdelay: debug
  filters:
    homeassistant.components.go2rtc:
      - "Could not find go2rtc docker binary"
    homeassistant.setup:
      - ".*go2rtc.*"
http:
  server_port: 8123
  use_x_forwarded_for: false
  trusted_proxies: []

discovery: